# Generated by Django 5.2.8 on 2025-11-12 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('name', models.CharField(help_text="e.g., 'Push Day', 'Leg Day'", max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('sets', models.PositiveIntegerField(help_text='Suggested number of sets')),
                ('reps', models.CharField(help_text="Suggested reps (e.g., '8-12', '10', '5x5')", max_length=50)),
                ('rest_period', models.PositiveIntegerField(blank=True, help_text='Rest period in seconds', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='UserProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('current_week', models.PositiveIntegerField(default=1)),
                ('current_day', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=200),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['is_public', 'difficulty_level'], name='programs_pr_is_publ_009cdb_idx'),
        ),
        migrations.AddField(
            model_name='programexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise'),
        ),
        migrations.AddField(
            model_name='programexercise',
            name='program_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='programs.programday'),
        ),
        migrations.AddField(
            model_name='programweek',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='programs.program'),
        ),
        migrations.AddField(
            model_name='programday',
            name='program_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='programs.programweek'),
        ),
        migrations.AddField(
            model_name='userprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='programs.program'),
        ),
        migrations.AddField(
            model_name='userprogram',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='programweek',
            unique_together={('program', 'week_number')},
        ),
        migrations.AlterUniqueTogether(
            name='programday',
            unique_together={('program_week', 'day_number')},
        ),
        migrations.AddIndex(
            model_name='userprogram',
            index=models.Index(fields=['user', 'is_active'], name='programs_us_user_id_d559c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogram',
            unique_together={('user', 'program')},
        ),
    ]
