# Generated by Django 5.2.8 on 2025-11-12 03:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('max_weight', 'Max Weight'), ('max_reps', 'Max Reps'), ('max_volume', 'Max Volume'), ('one_rep_max', 'One Rep Max (Estimated)')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_achieved', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to='workouts.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_records', to='workouts.workout')),
            ],
            options={
                'ordering': ['-date_achieved'],
                'indexes': [models.Index(fields=['user', 'exercise'], name='analytics_p_user_id_16816c_idx'), models.Index(fields=['date_achieved'], name='analytics_p_date_ac_326b7e_idx')],
                'unique_together': {('user', 'exercise', 'record_type')},
            },
        ),
        migrations.CreateModel(
            name='ProgressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('body_weight', models.DecimalField(blank=True, decimal_places=2, help_text="Weight in user's preferred unit", max_digits=5, null=True)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('neck', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hips', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('biceps', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('thighs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calves', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='progress_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='analytics_p_user_id_d7987e_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
